name = "funmon-api-v2"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" 
database_name = "funmon"
database_id = ""

[vars]
R2_ACCESS_KEY_ID = ""
R2_SECRET_ACCESS_KEY = ""
R2_BUCKET_NAME = "funmon"
R2_REGION = "auto" 
R2_ACCOUNT_ID = ""
API_KEY = ""

[observability]
enabled = true

